const actionTypes = {
  WEATHER_COORDS: "WEATHER_COORDS",
  WEATHER_COORDS_5_DAYS: "WEATHER_COORDS_5_DAYS",
  CITIES_LIST: "CITIES_LIST",
  FOUND_CITY: "FOUND_CITY",
  TOGGLE_SWOW: "TOGGLE_SWOW",
  INPUT_ERROR: "INPUT_ERROR",
};

export default actionTypes;
